### ISSUE TITLE
Add course info on website for courses in March

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#410]
Currently the website has the information on the previous course

![image](https://user-images.githubusercontent.com/14146757/69638455-0595e780-105b-11ea-830b-5725f20167c7.png)

Should we add one page per course in March? 

- `LMU Course 2020`
- `Uni Bielefeld Course 2020`

Or one page describing the flipped-classroom idea and then info on days + specifics on the two courses below?

- `Current Courses (2020)`

---

TODOs 

For each course:

- [x] Add links to videos + slides (#337 #455)
- [x] Add links to learnr tutorials (#451)
- [ ] Add links to exercises (#411 #423 #452 #453 #454)
- [x] Add links to code demos
- [ ] Add links to cheat sheets

Plus:

- [x] Change `content.Rmd` to contain all material regardless if used in courses.

**Comment by berndbischl** [comment]
we want to change this, yes.
maybe the menu should say "courses", then we have links to individual pages, one for each course.
and i would not include a "global setup". each course should simply explain itself. that seems more flexible.

ok?

**Comment by fabian-s** [comment]
see #309 as well

**Comment by HeidiSeibold** [comment]
see #406 and #407
